<div>
    <h1>Introduction to Python</h1>
</div>
<p>This notebook covers the basics of Python: variables, data types, loops, and functions.</p>
<p>
    Python has several built-in data types:
    <ul>
        <li><strong>Integers</strong>: Whole numbers (e.g., 1, 20, 100)</li>
        <li><strong>Floats</strong>: Decimal numbers (e.g., 1.5, 3.09)</li>
        <li><strong>Strings</strong>: Text data (e.g., "Hello, World!")</li>
        <li><strong>Lists</strong>: Ordered collections of values (e.g., ["Tehran", "Shiraz", "Yazd"])</li>
        <li><strong>Dictionaries</strong>: Key-value pairs (e.g., {"Iran": 90, "Turkey": 60, "Germany": 80})</li>
        <li><strong>Tuples</strong>: Immutable ordered collections (e.g., (3, 5, 6, 8))</li>
    </ul>
</p>


<p>In Python, we work with different <strong>data types</strong> (such as integers, strings, lists, and dictionaries).  
Each data type comes with its own <strong>functions</strong>, <strong>methods</strong>, and <strong>properties</strong>.  

- **Functions** are general tools we can use on many objects (e.g., `len()` gives the length of a list or a string).  
- **Methods** are actions that belong to a specific data type (e.g., `"hello".upper()` is a method for strings).  
- **Properties/Attributes** are characteristics of an object (for example, the shape of a NumPy array or the dtype of a Pandas Series).  

This means that every dataset or object in Python can have its own specific behaviors depending on its type.
</p>

<div>
    <h2>1. operations in python</h2>
</div>

<div>
    <h3>1.1 Math operations</h3>
</div>

In [6]:
a = 10
b = 3

print(a + b)  # Addition → 13
print(a - b)  # Subtraction → 7
print(a * b)  # Multiplication → 30
print(a / b)  # Division → 3.3333...
print(a // b) # Floor division → 3
print(a % b)  # Modulus → 1
print(a ** b) # Exponentiation (10^3) → 1000


13
7
30
3.3333333333333335
3
1
1000


<div>
    <h3>1.2 Rational operations</h3>
</div>

In [9]:
a = 13
b = 33
print(a<b)

True


In [11]:
print(a>b)

False


In [13]:
print(a == b)

False


In [15]:
print(a != b)

True


In [17]:
print(a<=b)

True


In [19]:
print(a>=b)

False


<div>
    <h3>1.3 Logical operations</h3>
</div>

In [22]:
a = True
b = False

In [24]:
print(a and b)

False


In [26]:
print(a or b)

True


In [28]:
print(not a)

False


In [30]:
True + True

2

In [32]:
True + False

1

<div>
    <h3>1.4 Assignment operations</h3>
</div>

In [35]:
a = 10
b = 5
b -= a
b

-5

In [37]:
c = 10
d = 5
d+=c
d

15

In [39]:
d *=c
d

150

<div>
    <h2>2. Python Data Types</h2>
</div>

<div>
    <h3>2.1 String</h3>
</div>

In [43]:
#String Functions
x = 'python' #returns the length of the string
len(x)

6

In [45]:
x = 100  #converts an object to string
x = str(x)

In [47]:
type(x)

str

In [49]:
#String Methods

| Method | Description | Example | Output |
|--------|-------------|---------|--------|
| `upper()` | Converts the string to uppercase. | `"hello".upper()` | `"HELLO"` |
| `lower()` | Converts the string to lowercase. | `"HELLO".lower()` | `"hello"` |
| `title()` | Capitalizes the first letter of each word. | `"hello world".title()` | `"Hello World"` |
| `capitalize()` | Capitalizes the first letter of the string. | `"python".capitalize()` | `"Python"` |
| `strip()` | Removes leading and trailing whitespace. | `"  hello  ".strip()` | `"hello"` |
| `lstrip()` | Removes leading whitespace. | `"  hello  ".lstrip()` | `"hello  "` |
| `rstrip()` | Removes trailing whitespace. | `"  hello  ".rstrip()` | `"  hello"` |
| `replace(old, new)` | Replaces occurrences of `old` with `new`. | `"hello world".replace("world", "Python")` | `"hello Python"` |
| `split(separator)` | Splits the string into a list. | `"apple,banana,grape".split(",")` | `['apple', 'banana', 'grape']` |
| `join(iterable)` | Joins elements of an iterable into a string. | `"-".join(["a", "b", "c"])` | `"a-b-c"` |
| `find(substring)` | Returns the index of the first occurrence of `substring`. | `"hello".find("l")` | `2` |
| `index(substring)` | Same as `find()`, but raises an error if not found. | `"hello".index("l")` | `2` |
| `count(substring)` | Counts occurrences of `substring`. | `"banana".count("a")` | `3` |
| `startswith(prefix)` | Checks if the string starts with `prefix`. | `"hello".startswith("he")` | `True` |
| `endswith(suffix)` | Checks if the string ends with `suffix`. | `"hello".endswith("o")` | `True` |
| `isdigit()` | Checks if the string consists only of digits. | `"123".isdigit()` | `True` |
| `isalpha()` | Checks if the string consists only of letters. | `"hello".isalpha()` | `True` |
| `isalnum()` | Checks if the string consists only of letters and digits. | `"hello123".isalnum()` | `True` |
| `isspace()` | Checks if the string consists only of whitespace. | `"   ".isspace()` | `True` |
| `swapcase()` | Swaps uppercase and lowercase letters. | `"Hello".swapcase()` | `"hELLO"` |
| `zfill(width)` | Pads the string with zeros until it reaches `width` length. | `"42".zfill(5)` | `"00042"` |


In [58]:
string = 'Hello, World!'
string.upper()

'HELLO, WORLD!'

In [60]:
string.lower()

'hello, world!'

In [62]:
string.title()

'Hello, World!'

In [64]:
string.capitalize()

'Hello, world!'

In [66]:
string2 = ' Hello! world     '
string.strip('')

'Hello, World!'

In [68]:
string2.lstrip()

'Hello! world     '

In [70]:
string.replace('Hello','hi')

'hi, World!'

In [72]:
string.split(',')

['Hello', ' World!']

In [74]:
string.index('H')

0

In [76]:
string.count('l')

3

<div>
     <h3> 2.2 Lists </h3>
</div>

In [79]:
list1 = ['apple','banana','Orange', 'Strawberry', 'Mango']
len(list1)

5

In [81]:
list2 = [1,4,2,8,3,5,9, 6,7,0]
sorted(list2)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [83]:
max(list2)

9

| Method                  | Description                                                    | Example               |
|-------------------------|----------------------------------------------------------------|-----------------------|
| `append(x)`             | Adds item `x` to the end of the list.                         | `lst.append(5)`       |
| `extend(iterable)`      | Extends the list by appending elements from an iterable.       | `lst.extend([6, 7])`  |
| `insert(i, x)`          | Inserts item `x` at position `i`.                             | `lst.insert(1, 5)`    |
| `remove(x)`             | Removes the first occurrence of item `x`.                     | `lst.remove(5)`       |
| `pop([i])`              | Removes and returns the item at position `i`.                 | `lst.pop(2)`          |
| `clear()`               | Removes all items from the list.                              | `lst.clear()`         |
| `index(x[, start, end])`| Returns the index of the first occurrence of item `x`.        | `lst.index(3)`        |
| `count(x)`              | Returns the number of occurrences of item `x`.                | `lst.count(3)`        |
| `sort(key, reverse)`    | Sorts the list in ascending order.                            | `lst.sort(reverse=True)`|
| `reverse()`             | Reverses the elements of the list in place.                   | `lst.reverse()`       |
| `copy()`                | Returns a shallow copy of the list.                           | `lst_copy = lst.copy()`|
| `join()`                | Joins the elements of a list of strings into one string.      | `", ".join(lst)`      |

In [86]:
# Creating a list
lst = [1, 2, 3, 4]
lst

[1, 2, 3, 4]

In [88]:
# append() - Adds an element to the end
lst.append(5)
lst

[1, 2, 3, 4, 5]

In [90]:
# extend() - Adds multiple elements
lst.extend([6, 7])  
lst

[1, 2, 3, 4, 5, 6, 7]

In [92]:
# insert() - Inserts an element at a specific index
lst.insert(2, 10) 
lst

[1, 2, 10, 3, 4, 5, 6, 7]

In [94]:
# remove() - Removes the first occurrence of an element
lst.remove(10)

In [96]:
# pop() - Removes and returns an element (default is last element)
removed_item = lst.pop(1) 
removed_item

2

In [98]:
lst.clear() 

In [100]:
lst

[]

In [102]:
lst = [1, 2, 3, 4]
index_of_3 = lst.index(3)
index_of_3

2

In [104]:
# count() - Counts occurrences of an element
lst.count(3)

1

In [106]:
# sort() - Sorts the list in ascending order
lst = [4, 1, 3, 2]
lst.sort() 

In [108]:
lst

[1, 2, 3, 4]

In [110]:
# reverse() - Reverses the order of the list
lst.reverse()
lst

[4, 3, 2, 1]

In [112]:
# copy() - Creates a copy of the list
lst_copy = lst.copy() 

In [114]:
words = ["Python", "is", "fun"]
sentence = " ".join(words)
sentence

'Python is fun'

In [116]:
words

['Python', 'is', 'fun']

In [118]:
#Selecting in Lists
list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 19, 11, 12, 14, 19, 20]

In [120]:
list[1]

2

In [122]:
list[:5]

[1, 2, 3, 4, 5]

In [124]:
zz = list[-1]
type(zz)

int

In [126]:
#list[start:stop:step]
list[1:5:2]

[2, 4]

In [128]:
list2 =[[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]]
jj = list2[0]
type(jj)

list

In [130]:
list2[0][1]

2

In [132]:
min(list2)

[1, 2, 3]

In [134]:
sum(list)

140

In [136]:
len(list2)

3

In [138]:
2 in list

True

In [140]:
list3 = [x**2 for x in range(6)]
list3

[0, 1, 4, 9, 16, 25]

In [142]:
numbers = [10, 20, 30, 40, 50]

In [144]:
max(numbers)

50

In [146]:
sum(numbers)

150

In [148]:
list4 = [1,2,3,4,5,6,7]
list4[1]

2

In [150]:
list4[1] = 100
list4

[1, 100, 3, 4, 5, 6, 7]

In [152]:
list4[0:2] = [101,102]
list4

[101, 102, 3, 4, 5, 6, 7]

In [154]:
list5 = [8,9,10]
list4 + list5

[101, 102, 3, 4, 5, 6, 7, 8, 9, 10]

In [156]:
del list4[1]

In [158]:
list4

[101, 3, 4, 5, 6, 7]

In [160]:
list4

[101, 3, 4, 5, 6, 7]

In [162]:
list4[0] = 2
list4

[2, 3, 4, 5, 6, 7]

<div>
    <h4>"The problem with lists is that we cannot directly perform mathematical operations on them. To handle numerical computations efficiently, we can use arrays instead. We'll work on that later."
    </h4>
</div>

In [165]:
numbers *2

[10, 20, 30, 40, 50, 10, 20, 30, 40, 50]

<div>
    <h3>
        2.3 Dictionary
    </h3>
</div>

In [168]:
data = {"name": "Alice", "age": 25, 'weight': 53, 'height': 167}

In [170]:
data.keys()        # Returns dict_keys(['name', 'age'])

dict_keys(['name', 'age', 'weight', 'height'])

In [172]:
data.values()      # Returns dict_values(['Alice', 25])

dict_values(['Alice', 25, 53, 167])

In [174]:
data.items()       # Returns dict_items([('name', 'Alice'), ('age', 25)])

dict_items([('name', 'Alice'), ('age', 25), ('weight', 53), ('height', 167)])

In [176]:
data.get("name")   # Get value of key → "Alice"

'Alice'

In [178]:
data.update({"city": "Berlin"})  # Adds new key-value pair

In [180]:
data

{'name': 'Alice', 'age': 25, 'weight': 53, 'height': 167, 'city': 'Berlin'}

In [182]:
data.pop("age")    # Removes key "age"

25

In [184]:
data

{'name': 'Alice', 'weight': 53, 'height': 167, 'city': 'Berlin'}

<div>
    <h2>
        3. Import libraries
    </h2>
</div>

<div>
    <h2> 3.1 Numpy </h2>
</div>

<div>
    <h4>
        The NumPy (numpy) library is used in Python for efficient numerical computing. It provides powerful tools for working with arrays, matrices, and mathematical operations.
    </h4>
</div>

In [189]:
import numpy as np

In [191]:
np.array([1,2,3,4,5,5,6])

array([1, 2, 3, 4, 5, 5, 6])

In [193]:
weight = np.array([67, 72, 89, 90])

In [195]:
weight *2

array([134, 144, 178, 180])

In [197]:
y = np.array ([[3,5,6,7],
               [6,7,8,9],
               [7,8,9,1]])
y

array([[3, 5, 6, 7],
       [6, 7, 8, 9],
       [7, 8, 9, 1]])

In [199]:
y[1]

array([6, 7, 8, 9])

In [201]:
y[2][0]

7

In [203]:
y[0:2,2:]
# y[rows, columns]

array([[6, 7],
       [8, 9]])

In [205]:
y > 6

array([[False, False, False,  True],
       [False,  True,  True,  True],
       [ True,  True,  True, False]])

In [207]:
np.random.seed(123)
np.random.rand()

0.6964691855978616

In [209]:
type(y)

numpy.ndarray

In [211]:
arr = np.array([[1, 2, 3],[4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [213]:
# Basic Properties of NumPy Arrays
arr.shape

(2, 3)

In [215]:
arr.ndim

2

In [217]:
arr.size

6

In [219]:
arr.dtype

dtype('int64')

In [221]:
arr.itemsize

8

In [223]:
arr.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [225]:
arr.nbytes

48

<div>
    <h2> Basic Properties of NumPy Arrays Methods 
    </h2>
</div>

In [228]:
#Array Manipulation Methods
arr2 = np.array([[1, 2, 3, 4],[5, 6, 7, 8]])
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [230]:
arr2.reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [232]:
arr2.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [234]:
arr2.copy()

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [236]:
# Mathematical & Statistical Methods
arr3 = np.array([1, 3, 6, 9, 12, 15])
arr3

array([ 1,  3,  6,  9, 12, 15])

In [238]:
arr3.sum()

46

In [240]:
arr3.min()

1

In [242]:
arr3.max()

15

In [244]:
arr3.mean()

7.666666666666667

In [246]:
arr3.std()

4.887626099538393

In [248]:
arr3.var()

23.888888888888886

In [250]:
arr3.prod()

29160

In [252]:
arr3.cumsum()

array([ 1,  4, 10, 19, 31, 46])

In [254]:
arr.cumprod()

array([  1,   2,   6,  24, 120, 720])

In [256]:
# Sorting & Searching Methods
arr4 = np.array([4,1,5,7,9,0,12,3,40])
arr4

array([ 4,  1,  5,  7,  9,  0, 12,  3, 40])

In [258]:
np.sort(arr4)   # This change will apply on arr4

array([ 0,  1,  3,  4,  5,  7,  9, 12, 40])

In [260]:
arr5 = np.array([[7,8,5],
                 [4,9,3]])
arr5

array([[7, 8, 5],
       [4, 9, 3]])

In [262]:
arr5.sort() #sorted by row - default
arr5

array([[5, 7, 8],
       [3, 4, 9]])

In [264]:
arr5.sort(axis=0)
arr5

array([[3, 4, 8],
       [5, 7, 9]])

In [266]:
np.argsort(arr4)

array([5, 1, 7, 0, 2, 3, 4, 6, 8])

In [268]:
np.where(arr4 > 8)

(array([4, 6, 8]),)

<div>
    <h2> Basic Properties of NumPy Methods 
    </h2>
</div>

In [271]:
arr1 =np.array([1,2,3])
arr1

array([1, 2, 3])

In [273]:
np.zeros((2,3)) #create an array of zeros  

array([[0., 0., 0.],
       [0., 0., 0.]])

In [275]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [277]:
np.sum(arr1)

6

In [279]:
np.mean(arr1)

2.0

In [281]:
np.add(arr4,100)   # not permanent

array([104, 101, 105, 107, 109, 100, 112, 103, 140])

In [283]:
np.subtract(arr4,1)

array([ 3,  0,  4,  6,  8, -1, 11,  2, 39])

In [285]:
np.multiply(arr4, 2)

array([ 8,  2, 10, 14, 18,  0, 24,  6, 80])

In [287]:
np.divide(arr4, 2)

array([ 2. ,  0.5,  2.5,  3.5,  4.5,  0. ,  6. ,  1.5, 20. ])

In [289]:
np.power(arr4, 2)

array([  16,    1,   25,   49,   81,    0,  144,    9, 1600])

In [291]:
print(np.random.randint(1, 10, 5)) # 5 random integers from 1 to 9
print(np.random.rand(3))           # 3 random floats (0 to 1)
print(np.random.normal(0, 1, 5))   # 5 random numbers from normal distribution

[3 3 7 2 4]
[0.49111893 0.78002776 0.41092437]
[-1.07746533  0.23848917  1.67960037 -1.30580313 -1.13889525]


In [293]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [295]:
np.multiply(A,B)

array([[ 5, 12],
       [21, 32]])

In [297]:
x = np.array([1, 2, 3])
z = np.array([4, 5, 6])

In [299]:
np.vstack([x,z])

array([[1, 2, 3],
       [4, 5, 6]])

In [301]:
np.hstack([x,z])

array([1, 2, 3, 4, 5, 6])

In [303]:
arr5 = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [5, 9, 0, 3]])

In [305]:
arr5[1]

array([5, 6, 7, 8])

In [307]:
arr5[0][1]

2

In [309]:
arr5[:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [311]:
arr5[:,2:]

array([[3, 4],
       [7, 8],
       [0, 3]])

In [313]:
arr5 > 4

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True, False, False]])

In [315]:
arr5[arr5 > 4]

array([5, 6, 7, 8, 5, 9])

<div>
    <h2> 3.2 Pandas</h2>
</div>

<div>
    <h4>
        Pandas is a Python library used for data manipulation, analysis, and cleaning. It provides fast and flexible tools to work with structured data, such as tables (DataFrames) and series (1D data). </h4>
</div>

<p>
    Key Reasons to Use Pandas:
    <ul>
        <li> Handles large datasets efficiently</li>
        <li> Supports data cleaning and preprocessing</li>
        <li> Works well with NumPy, Matplotlib, and SQL</li>
        <li> Provides built-in statistical and mathematical functions</li>
        <li> Can read and write multiple file formats (CSV, Excel, SQL, JSON, etc.)</li>
    </ul>
</p>


In [319]:
import pandas as pd

<div>
    <h2>
        DataFrame
    </h2>
</div>

In [322]:
# Create a DataFrame from a Dictionary
data = {
    "name" : ["alice", "anna", "jack", "july"],
    "lastname" : ["kepit", "kia", "muler" , "summet"],
    "age" : [24, 28, 25, 31],
    "job" : ["student", "engineer", "doctor", "teacher"]
}
print(data)

{'name': ['alice', 'anna', 'jack', 'july'], 'lastname': ['kepit', 'kia', 'muler', 'summet'], 'age': [24, 28, 25, 31], 'job': ['student', 'engineer', 'doctor', 'teacher']}


In [324]:
df = pd.DataFrame(data)
df

name lastname  age       job
0  alice    kepit   24   student
1   anna      kia   28  engineer
2   jack    muler   25    doctor
3   july   summet   31   teacher

In [326]:
# DataFrame Properties (Attributes)
df.shape

(4, 4)

In [328]:
df.size

16

In [330]:
df.dtypes

name        object
lastname    object
age          int64
job         object
dtype: object

In [332]:
df.columns

Index(['name', 'lastname', 'age', 'job'], dtype='object')

In [334]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [336]:
df.head()

name lastname  age       job
0  alice    kepit   24   student
1   anna      kia   28  engineer
2   jack    muler   25    doctor
3   july   summet   31   teacher

In [338]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   name      4 non-null      object
 1   lastname  4 non-null      object
 2   age       4 non-null      int64 
 3   job       4 non-null      object
dtypes: int64(1), object(3)
memory usage: 260.0+ bytes


In [340]:
df.describe()

age
count   4.000000
mean   27.000000
std     3.162278
min    24.000000
25%    24.750000
50%    26.500000
75%    28.750000
max    31.000000

<h3>Data Selecting and Cutting</h3>

In [343]:
df2 = pd.read_csv('Downloads/ipynbs/mini.csv')
df2

name      breed  color  height  weight date of birth
0    bella   Labrador  brown      56      24    2013-07-01
1  charlie     poodle  black      43      24    2016-09-16
2     lucy  chow chow  brown      46      24    2014-08-25
3   cooper  schnauzer   gray      49      17    2011-12-11
4      max   Labrador  black      59      29    2017-01-20
5   stella  chihuahua    Tan      18       2    2015-04-20
6   bernie    bernard  white      77      74    2018-02-27

In [345]:
# Access a Single Column
df2[["name"]]

name
0    bella
1  charlie
2     lucy
3   cooper
4      max
5   stella
6   bernie

In [347]:
# Access a list of Columns

df2[["name", "date of birth"]]

name date of birth
0    bella    2013-07-01
1  charlie    2016-09-16
2     lucy    2014-08-25
3   cooper    2011-12-11
4      max    2017-01-20
5   stella    2015-04-20
6   bernie    2018-02-27

In [349]:
# loc & iloc --- work on rows
df2.loc[[1]]

name   breed  color  height  weight date of birth
1  charlie  poodle  black      43      24    2016-09-16

In [351]:
df2.iloc[[1]]

name   breed  color  height  weight date of birth
1  charlie  poodle  black      43      24    2016-09-16

In [353]:
# Adding a New Column
df2["city"] = ["teharn", "berlin", "paris", "paris", "berlin", "paris", "teharn"]
df2

name      breed  color  height  weight date of birth    city
0    bella   Labrador  brown      56      24    2013-07-01  teharn
1  charlie     poodle  black      43      24    2016-09-16  berlin
2     lucy  chow chow  brown      46      24    2014-08-25   paris
3   cooper  schnauzer   gray      49      17    2011-12-11   paris
4      max   Labrador  black      59      29    2017-01-20  berlin
5   stella  chihuahua    Tan      18       2    2015-04-20   paris
6   bernie    bernard  white      77      74    2018-02-27  teharn

In [355]:
# Adding a New Row
df2.loc[len(df2)] = ['cele', 'poodle', 'gray', 54, 32, '2011-06-11', 'tehran']

In [357]:
# Dropping a column
df2.drop(columns = ['color'])

name      breed  height  weight date of birth    city
0    bella   Labrador      56      24    2013-07-01  teharn
1  charlie     poodle      43      24    2016-09-16  berlin
2     lucy  chow chow      46      24    2014-08-25   paris
3   cooper  schnauzer      49      17    2011-12-11   paris
4      max   Labrador      59      29    2017-01-20  berlin
5   stella  chihuahua      18       2    2015-04-20   paris
6   bernie    bernard      77      74    2018-02-27  teharn
7     cele     poodle      54      32    2011-06-11  tehran

In [359]:
# Dropping a row
df2.drop(index = 1)

name      breed  color  height  weight date of birth    city
0   bella   Labrador  brown      56      24    2013-07-01  teharn
2    lucy  chow chow  brown      46      24    2014-08-25   paris
3  cooper  schnauzer   gray      49      17    2011-12-11   paris
4     max   Labrador  black      59      29    2017-01-20  berlin
5  stella  chihuahua    Tan      18       2    2015-04-20   paris
6  bernie    bernard  white      77      74    2018-02-27  teharn
7    cele     poodle   gray      54      32    2011-06-11  tehran

In [361]:
df2['index'] = ['num1','num2','num3','num4','num5', 'num6','num7', 'num8']
df2

name      breed  color  height  weight date of birth    city index
0    bella   Labrador  brown      56      24    2013-07-01  teharn  num1
1  charlie     poodle  black      43      24    2016-09-16  berlin  num2
2     lucy  chow chow  brown      46      24    2014-08-25   paris  num3
3   cooper  schnauzer   gray      49      17    2011-12-11   paris  num4
4      max   Labrador  black      59      29    2017-01-20  berlin  num5
5   stella  chihuahua    Tan      18       2    2015-04-20   paris  num6
6   bernie    bernard  white      77      74    2018-02-27  teharn  num7
7     cele     poodle   gray      54      32    2011-06-11  tehran  num8

In [363]:
df2.set_index('index', inplace=True)

In [365]:
df2

name      breed  color  height  weight date of birth    city
index                                                                 
num1     bella   Labrador  brown      56      24    2013-07-01  teharn
num2   charlie     poodle  black      43      24    2016-09-16  berlin
num3      lucy  chow chow  brown      46      24    2014-08-25   paris
num4    cooper  schnauzer   gray      49      17    2011-12-11   paris
num5       max   Labrador  black      59      29    2017-01-20  berlin
num6    stella  chihuahua    Tan      18       2    2015-04-20   paris
num7    bernie    bernard  white      77      74    2018-02-27  teharn
num8      cele     poodle   gray      54      32    2011-06-11  tehran

In [367]:
df2.rename(columns = {'city':'cities'}, inplace = True)

In [369]:
df2

name      breed  color  height  weight date of birth  cities
index                                                                 
num1     bella   Labrador  brown      56      24    2013-07-01  teharn
num2   charlie     poodle  black      43      24    2016-09-16  berlin
num3      lucy  chow chow  brown      46      24    2014-08-25   paris
num4    cooper  schnauzer   gray      49      17    2011-12-11   paris
num5       max   Labrador  black      59      29    2017-01-20  berlin
num6    stella  chihuahua    Tan      18       2    2015-04-20   paris
num7    bernie    bernard  white      77      74    2018-02-27  teharn
num8      cele     poodle   gray      54      32    2011-06-11  tehran

In [371]:
df2.index = [101, 102, 103, 104, 105, 106, 107,108]

In [373]:
df2

name      breed  color  height  weight date of birth  cities
101    bella   Labrador  brown      56      24    2013-07-01  teharn
102  charlie     poodle  black      43      24    2016-09-16  berlin
103     lucy  chow chow  brown      46      24    2014-08-25   paris
104   cooper  schnauzer   gray      49      17    2011-12-11   paris
105      max   Labrador  black      59      29    2017-01-20  berlin
106   stella  chihuahua    Tan      18       2    2015-04-20   paris
107   bernie    bernard  white      77      74    2018-02-27  teharn
108     cele     poodle   gray      54      32    2011-06-11  tehran

In [375]:
df2.insert(6, "country", ["iran", "germany", "france", "france", "germany", "france", "iran", "iran"])
df2

name      breed  color  height  weight date of birth  country  cities
101    bella   Labrador  brown      56      24    2013-07-01     iran  teharn
102  charlie     poodle  black      43      24    2016-09-16  germany  berlin
103     lucy  chow chow  brown      46      24    2014-08-25   france   paris
104   cooper  schnauzer   gray      49      17    2011-12-11   france   paris
105      max   Labrador  black      59      29    2017-01-20  germany  berlin
106   stella  chihuahua    Tan      18       2    2015-04-20   france   paris
107   bernie    bernard  white      77      74    2018-02-27     iran  teharn
108     cele     poodle   gray      54      32    2011-06-11     iran  tehran

In [377]:
df2[["name", "breed"]]

name      breed
101    bella   Labrador
102  charlie     poodle
103     lucy  chow chow
104   cooper  schnauzer
105      max   Labrador
106   stella  chihuahua
107   bernie    bernard
108     cele     poodle

In [379]:
df2.loc[[101,]]

name     breed  color  height  weight date of birth country  cities
101  bella  Labrador  brown      56      24    2013-07-01    iran  teharn

In [381]:
df2.iloc[[1]]

name   breed  color  height  weight date of birth  country  cities
102  charlie  poodle  black      43      24    2016-09-16  germany  berlin

In [383]:
df2.loc[[101, 102, 103], ["name", "color"]]

name  color
101    bella  brown
102  charlie  black
103     lucy  brown

In [385]:
df2.iloc[[0,1,2], [0,1]]

name      breed
101    bella   Labrador
102  charlie     poodle
103     lucy  chow chow

In [387]:
df2.sort_values(["height"]) 

name      breed  color  height  weight date of birth  country  cities
106   stella  chihuahua    Tan      18       2    2015-04-20   france   paris
102  charlie     poodle  black      43      24    2016-09-16  germany  berlin
103     lucy  chow chow  brown      46      24    2014-08-25   france   paris
104   cooper  schnauzer   gray      49      17    2011-12-11   france   paris
108     cele     poodle   gray      54      32    2011-06-11     iran  tehran
101    bella   Labrador  brown      56      24    2013-07-01     iran  teharn
105      max   Labrador  black      59      29    2017-01-20  germany  berlin
107   bernie    bernard  white      77      74    2018-02-27     iran  teharn

In [389]:
df2[["height"]] == 54 

height
101   False
102   False
103   False
104   False
105   False
106   False
107   False
108    True

In [391]:
df2[df2[["height"]] == 54]

name breed color  height  weight date of birth country cities
101  NaN   NaN   NaN     NaN     NaN           NaN     NaN    NaN
102  NaN   NaN   NaN     NaN     NaN           NaN     NaN    NaN
103  NaN   NaN   NaN     NaN     NaN           NaN     NaN    NaN
104  NaN   NaN   NaN     NaN     NaN           NaN     NaN    NaN
105  NaN   NaN   NaN     NaN     NaN           NaN     NaN    NaN
106  NaN   NaN   NaN     NaN     NaN           NaN     NaN    NaN
107  NaN   NaN   NaN     NaN     NaN           NaN     NaN    NaN
108  NaN   NaN   NaN    54.0     NaN           NaN     NaN    NaN

In [397]:
df2[(df2["color"]== 'gray') | (df2["cities"]== 'tehran')]

name      breed color  height  weight date of birth country  cities
104  cooper  schnauzer  gray      49      17    2011-12-11  france   paris
108    cele     poodle  gray      54      32    2011-06-11    iran  tehran

In [399]:
df2[(df2["name"]== "stella") & (df2["color"]== "Tan")]

name      breed color  height  weight date of birth country cities
106  stella  chihuahua   Tan      18       2    2015-04-20  france  paris

In [401]:
x = np.logical_or(df2["name"] == "max", df2["breed"]== "poodle")
df2[x]

name     breed  color  height  weight date of birth  country  cities
102  charlie    poodle  black      43      24    2016-09-16  germany  berlin
105      max  Labrador  black      59      29    2017-01-20  germany  berlin
108     cele    poodle   gray      54      32    2011-06-11     iran  tehran

In [403]:
df2[np.logical_and(df2["name"] == "cele", df2["breed"]== "poodle")]

name   breed color  height  weight date of birth country  cities
108  cele  poodle  gray      54      32    2011-06-11    iran  tehran

In [405]:
#.isin
df2[df2["height"].isin([18, 59, 77])]

name      breed  color  height  weight date of birth  country  cities
105     max   Labrador  black      59      29    2017-01-20  germany  berlin
106  stella  chihuahua    Tan      18       2    2015-04-20   france   paris
107  bernie    bernard  white      77      74    2018-02-27     iran  teharn

In [407]:
df2["height"].mean()

50.25

In [409]:
df2[df2['weight']> 25]

name     breed  color  height  weight date of birth  country  cities
105     max  Labrador  black      59      29    2017-01-20  germany  berlin
107  bernie   bernard  white      77      74    2018-02-27     iran  teharn
108    cele    poodle   gray      54      32    2011-06-11     iran  tehran

In [411]:
df3 = df2.sort_values(by = "weight")
df3

name      breed  color  height  weight date of birth  country  cities
106   stella  chihuahua    Tan      18       2    2015-04-20   france   paris
104   cooper  schnauzer   gray      49      17    2011-12-11   france   paris
101    bella   Labrador  brown      56      24    2013-07-01     iran  teharn
102  charlie     poodle  black      43      24    2016-09-16  germany  berlin
103     lucy  chow chow  brown      46      24    2014-08-25   france   paris
105      max   Labrador  black      59      29    2017-01-20  germany  berlin
108     cele     poodle   gray      54      32    2011-06-11     iran  tehran
107   bernie    bernard  white      77      74    2018-02-27     iran  teharn

In [413]:
df3.reset_index(drop = True)

name      breed  color  height  weight date of birth  country  cities
0   stella  chihuahua    Tan      18       2    2015-04-20   france   paris
1   cooper  schnauzer   gray      49      17    2011-12-11   france   paris
2    bella   Labrador  brown      56      24    2013-07-01     iran  teharn
3  charlie     poodle  black      43      24    2016-09-16  germany  berlin
4     lucy  chow chow  brown      46      24    2014-08-25   france   paris
5      max   Labrador  black      59      29    2017-01-20  germany  berlin
6     cele     poodle   gray      54      32    2011-06-11     iran  tehran
7   bernie    bernard  white      77      74    2018-02-27     iran  teharn

In [415]:
df2.pivot_table(values = "weight", index = "color", aggfunc = "mean")

weight
color        
Tan       2.0
black    26.5
brown    24.0
gray     24.5
white    74.0

In [417]:
pd.DataFrame(df2.groupby('color')["weight"].mean())

weight
color        
Tan       2.0
black    26.5
brown    24.0
gray     24.5
white    74.0

In [419]:
pd.DataFrame(df2.groupby(["country", "color"])["weight"].mean())

weight
country color        
france  Tan       2.0
        brown    24.0
        gray     17.0
germany black    26.5
iran    brown    24.0
        gray     32.0
        white    74.0

In [421]:
df2.groupby("color")["weight"].mean()

color
Tan       2.0
black    26.5
brown    24.0
gray     24.5
white    74.0
Name: weight, dtype: float64

In [423]:
pd.DataFrame(df2.groupby("color")["weight"].mean())

weight
color        
Tan       2.0
black    26.5
brown    24.0
gray     24.5
white    74.0

In [425]:
df2.groupby("color")["weight"].agg([min, max])

/var/folders/8v/j04s7d697pbchpncxsv_q5zw0000gn/T/ipykernel_1783/1035039177.py:1: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  df2.groupby("color")["weight"].agg([min, max])
/var/folders/8v/j04s7d697pbchpncxsv_q5zw0000gn/T/ipykernel_1783/1035039177.py:1: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  df2.groupby("color")["weight"].agg([min, max])


min  max
color          
Tan      2    2
black   24   29
brown   24   24
gray    17   32
white   74   74

In [427]:
df2.groupby(["color", "breed"])[["weight", "height"]].mean()

weight  height
color breed                    
Tan   chihuahua     2.0    18.0
black Labrador     29.0    59.0
      poodle       24.0    43.0
brown Labrador     24.0    56.0
      chow chow    24.0    46.0
gray  poodle       32.0    54.0
      schnauzer    17.0    49.0
white bernard      74.0    77.0

<h2>4. Control Flow</h2>

<p>Control flow tools let you decide the order in which code runs.</p>

<h3>If Statements</h3>
<p>Used for making decisions in code (branching).</p>

<h3>Loops</h3>
<p>Used for repeating code:</p>
<ul>
  <li><b>while</b> → repeat while a condition is true.</li>
  <li><b>for</b> → repeat for each element in a sequence.</li>
</ul>


In [438]:
a = 10
if a%2 == 0:
    # do something
    print('it is even')
elif a%3 == 0:
    # do something else
    print('it is not even')
else:
    # do another thing
    print('it is add')


it is even


In [1]:
i = 1
while i < 6:
    print(i)
    i+=1

1
2
3
4
5


In [3]:
i = 1
while i < 6:
    print(i)
    i+=1
    if i == 3:
        break

1
2


In [5]:
fam = [1.73, 1.85, 1.92, 1,21]
fam

[1.73, 1.85, 1.92, 1, 21]

In [7]:
for i in fam:
    print(i)

1.73
1.85
1.92
1
21


<h2>Functions</h2>
<p>Functions allow reusing code and organizing logic.</p>

In [16]:
def add_numbers(a, b):
    return a + b

print(add_numbers(5, 7)) 

12
